title: Ryan Stofer
logo: /assets/img/Profile_Picture_Circle.png

description: >
  Data Scientist and Software Developer building data-driven applications,
  machine learning models, and analytics tools.

show_downloads: false

plugins:
  - jekyll-seo-tag

sass:
  style: compressed
